name: Sync Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-sync:
    name: Test and Sync repositories
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.API_TOKEN_GITHUB }}  # Use PAT for checkout
      
      # Rest of the setup and test steps remain the same...
      
      - name: Push to destination repository
        if: success() && steps.repo-state.outcome == 'success'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use PAT in the remote URL
          git remote add destination https://${{ secrets.API_TOKEN_GITHUB }}@github.com/mansi104-ai/bot_repo.git
          
          # Verify remote was added
          if ! git remote -v | grep -q destination; then
            echo "Failed to verify destination remote"
            exit 1
          fi
          
          # Try to push with error handling
          if ! git push destination main:main --force; then
            echo "Failed to push to destination repository"
            exit 1
          fi
          
          echo "Successfully synced repositories"