name: Sync to Bot Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to bot repository
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.name "mansi104-ai"
          git config --global user.email "mkb.kalra@gmail.com"
          
          # Remove old remote if exists
          git remote remove bot-repo 2>/dev/null || true
          
          # Add new remote with token
          git remote add bot-repo "https://mansi104-ai:${API_TOKEN_GITHUB}@github.com/mansi104-ai/bot_repo.git"
          
          # Push to bot repository
          git push -f bot-repo main:main
