name: Sync to Bot Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.name "mansi104-ai"
          git config --global user.email "mkb.kalra@gmail.com"
          
          # Ensure old remote is removed
          git remote remove bot-repo 2>/dev/null || true
          
          # Create the remote URL with explicit token
          REMOTE_URL="https://${{secrets.API_TOKEN_GITHUB}}@github.com/mansi104-ai/bot_repo.git"
          
          echo "Adding bot repository remote..."
          git remote add bot-repo "$REMOTE_URL"
          
          echo "Fetching from bot repository..."
          git fetch bot-repo
          
          echo "Current branch status:"
          git branch -a

          # Create a temporary branch without workflows
          git branch temp-branch
          git checkout temp-branch
          git rm -r --cached .github/workflows
          git commit -m "Remove workflows for sync"
          
          echo "Pushing to bot repository..."
          git push -f "https://${{ secrets.API_TOKEN_GITHUB}}@github.com/mansi104-ai/bot_repo.git" temp:main

          # Clean up
          git checkout main
          git branch -D temp-branch